export const QUESTIONS = [
  { id: 'a1', axis: 'belief', text: 'AI tools have the potential to meaningfully improve work quality in fields like medical education and healthcare communications.', lo: 'Strongly disagree', hi: 'Strongly agree' },
  { id: 'b1', axis: 'risk', text: "I'm concerned that AI could change professional roles in ways people aren't fully prepared for.", lo: 'Not at all concerned', hi: 'Very concerned' },
  { id: 'a2', axis: 'belief', text: 'Even an imperfect AI-generated starting point would save me meaningful time on tasks like writing, research, or document prep.', lo: 'Strongly disagree', hi: 'Strongly agree' },
  { id: 'b2', axis: 'risk', text: 'I worry that as AI takes on more writing and research tasks, deep subject-matter expertise will be valued less.', lo: 'Not at all', hi: 'A lot' },
  { id: 'a3', axis: 'belief', text: 'I believe AI can be used responsibly in regulated, compliance-sensitive industries.', lo: 'Strongly disagree', hi: 'Strongly agree' },
  { id: 'b3', axis: 'risk', text: 'I feel uncertain about what day-to-day work will look like in roles like mine as AI tools become more common.', lo: 'Not uncertain at all', hi: 'Very uncertain' },
  { id: 'a4', axis: 'belief', text: 'In general, I think the benefits of adopting AI tools in a professional setting outweigh the risks and adjustment costs.', lo: 'Strongly disagree', hi: 'Strongly agree' },
  { id: 'b4', axis: 'risk', text: "I have questions or concerns about AI that I haven't had a good opportunity to raise yet.", lo: 'None at all', hi: 'Several' },
  { id: 'a5', axis: 'belief', text: "I'm genuinely curious about how AI could change the way people work in fields like mine.", lo: 'Not curious at all', hi: 'Very curious' },
  { id: 'b5', axis: 'risk', text: 'When I think about how AI is changing the way professionals in my field will work, I feel more anxious than excited.', lo: 'Much more excited', hi: 'Much more anxious' },
]

export const USAGE_LEVELS = [
  {
    level: 0, label: 'Not yet using AI tools',
    desc: "Haven't used AI tools in a personal or professional context.",
    color: '#667788', bg: '#F4F7FA', border: '#CDD5DC',
    items: [
      { id: 'l0_a', text: "I have not used any AI tools (ChatGPT, Claude, Gemini, Copilot, etc.)" },
      { id: 'l0_b', text: "I've heard about AI tools but haven't tried any of them yet" },
      { id: 'l0_c', text: "I've actively chosen not to use AI tools" },
    ],
  },
  {
    level: 1, label: 'Occasional personal use',
    desc: 'Tried AI tools casually \u2014 for curiosity, personal questions, or one-off tasks.',
    color: '#2A85B8', bg: '#EEF7FC', border: '#A8D4EC',
    items: [
      { id: 'l1_a', text: 'Asked ChatGPT, Claude, or Gemini a general knowledge question' },
      { id: 'l1_b', text: 'Used AI to help write or improve a personal email or message' },
      { id: 'l1_c', text: 'Used an AI chatbot to explain a concept I was trying to understand' },
      { id: 'l1_d', text: 'Used AI to summarize an article or document I was reading personally' },
      { id: 'l1_e', text: 'Used an AI-powered search tool (Perplexity, Bing AI, Google AI Overviews)' },
      { id: 'l1_f', text: 'Used an AI image generator (DALL\u00b7E, Midjourney, Adobe Firefly)' },
      { id: 'l1_g', text: 'Used AI to look up a medical term, drug mechanism, or clinical concept' },
      { id: 'l1_h', text: 'Used AI to help understand a regulatory or compliance document' },
    ],
  },
  {
    level: 2, label: 'Regular use for work tasks',
    desc: 'Use AI for specific professional tasks \u2014 not necessarily as a repeatable workflow, but as a tool I reach for.',
    color: '#1a72a0', bg: '#E4F2FA', border: '#7FC4E5',
    items: [
      { id: 'l2_a', text: 'Used AI to draft or edit a grant proposal or letter of intent' },
      { id: 'l2_b', text: 'Used AI to draft or edit a needs assessment or statement of need' },
      { id: 'l2_c', text: 'Used AI to draft or edit learning objectives for a CME or IME program' },
      { id: 'l2_d', text: 'Used AI to draft or edit an educational program description or curriculum outline' },
      { id: 'l2_e', text: 'Used AI to brainstorm or refine program titles or session names' },
      { id: 'l2_f', text: 'Used AI to generate or explore instructional design concepts \u2014 formats, modalities, or session structures' },
      { id: 'l2_g', text: 'Used AI to develop faculty discussion questions, case scenarios, or interactive elements' },
      { id: 'l2_h', text: 'Used AI to draft or edit a budget narrative or program justification' },
      { id: 'l2_i', text: 'Used AI to research a therapeutic area, disease state, or treatment landscape' },
      { id: 'l2_j', text: 'Used AI to look up clinical trial results, FDA approvals, or pipeline updates' },
      { id: 'l2_k', text: 'Used AI to help frame or articulate a practice gap or unmet educational need' },
      { id: 'l2_l', text: 'Used AI to summarize a long clinical, scientific, or regulatory document' },
      { id: 'l2_m', text: 'Used AI to brainstorm ideas, create outlines, or structure a project' },
      { id: 'l2_n', text: 'Used AI to prepare talking points or content for a meeting or presentation' },
      { id: 'l2_o', text: 'Used Microsoft Copilot inside Word, Outlook, Teams, or PowerPoint' },
    ],
  },
  {
    level: 3, label: 'AI as part of a defined workflow',
    desc: "AI is a regular, deliberate step in how work gets done \u2014 part of the process, not just occasional help.",
    color: '#1A7A4A', bg: '#E8F5EE', border: '#7FC9A0',
    items: [
      { id: 'l3_a', text: 'Regularly use AI as a starting point when developing grant proposals or letters of intent \u2014 as a consistent first step, not a one-off' },
      { id: 'l3_b', text: 'Regularly use AI to build out needs assessments or statements of need before refining them myself' },
      { id: 'l3_c', text: 'Use AI as a standard step when drafting learning objectives \u2014 generate first, then evaluate and revise' },
      { id: 'l3_d', text: 'Use AI consistently when structuring educational program descriptions or curriculum outlines' },
      { id: 'l3_e', text: 'Use AI as a regular brainstorming partner for program titles and session names \u2014 part of how I start that work' },
      { id: 'l3_f', text: 'Use AI to generate instructional design options as a routine part of program planning, not just occasionally' },
      { id: 'l3_g', text: 'Regularly use AI to draft discussion questions, case scenarios, or faculty interaction elements as part of program development' },
      { id: 'l3_h', text: 'Use AI to draft budget narratives or justifications as a consistent step in my proposal process' },
      { id: 'l3_i', text: 'Used AI consistently at a specific point in a recurring work task' },
      { id: 'l3_j', text: 'Used AI to pull citations or references to verify or support my own writing' },
      { id: 'l3_k', text: 'Used AI to review and improve my own content before sharing it with others' },
      { id: 'l3_l', text: 'Used AI as part of a literature review, needs assessment, or research process' },
      { id: 'l3_m', text: 'Used AI to monitor changes in clinical guidelines, drug labeling, or REMS requirements' },
      { id: 'l3_n', text: 'Used AI to research funder priorities, past grants, or competitive landscape before a submission' },
      { id: 'l3_o', text: 'Developed a personal system of prompts or instructions I reuse across tasks' },
    ],
  },
  {
    level: 4, label: 'AI integrated into professional systems',
    desc: 'Work with AI tools embedded in formal organizational systems, platforms, or governed pipelines.',
    color: '#121531', bg: '#EEEEF8', border: '#9099C0',
    items: [
      { id: 'l4_a', text: 'Reviewed and approved AI-generated medical education content before it was used or submitted' },
      { id: 'l4_b', text: 'Used AI to generate or refine CME/IME learning objectives, needs assessments, or statements of need as part of a formal review process' },
      { id: 'l4_c', text: 'Used AI output as a starting point for a grant proposal that went through a formal review process before submission' },
      { id: 'l4_d', text: 'Participated in a workflow where AI flagged clinical or compliance issues for human review' },
      { id: 'l4_e', text: 'Used AI features built into professional software (Salesforce Einstein, Veeva, Epic, Microsoft Copilot for Enterprise, etc.)' },
      { id: 'l4_f', text: 'Reviewed, corrected, or formally approved AI-generated content before it was used' },
      { id: 'l4_g', text: 'Used AI tools connected to organizational data (CRM, shared documents, databases)' },
      { id: 'l4_h', text: 'Used AI to generate ranked recommendations or prioritization lists that informed a real decision' },
      { id: 'l4_i', text: 'Built, configured, or customized an AI prompt or workflow for a specific professional purpose' },
      { id: 'l4_j', text: 'Provided feedback on AI outputs that was captured and used to improve the system' },
    ],
  },
]

export const QUADRANTS = {
  Visionary: {
    color: '#1A7A4A', bg: '#E8F5EE', border: '#A7D7BC', icon: '\u25c6',
    tagline: "High belief in AI's potential \u2014 comfortable with the change ahead.",
    desc: "You see what this technology can do and you're not threatened by it. That's a real asset. You'll move through the training quickly and can serve as a resource for colleagues who are still finding their footing.",
    training: "In the live calibration session, you're a likely peer mentor.",
  },
  Disruptor: {
    color: '#B45309', bg: '#FFFBEB', border: '#FCD34D', icon: '\u25b2',
    tagline: "High belief in AI's potential \u2014 and real questions about what it means for you personally.",
    desc: "You understand what this technology can do, and you're taking it seriously. That combination of belief and honest concern is exactly the right starting place. Your clinical expertise and judgment are not replaceable \u2014 the system is architecturally built around that fact. Nothing gets submitted without your review and approval.",
    training: 'Your questions will make the calibration session better. The training is specifically designed for where you are right now.',
  },
  Endangered: {
    color: '#9B1C1C', bg: '#FEF2F2', border: '#FCA5A5', icon: '\u25cf',
    tagline: 'Skeptical of what AI can deliver \u2014 and concerned about personal impact.',
    desc: "You have doubts about what AI can actually do, and you're worried about what it means for your role. Both are fair positions. The training won't try to talk you out of your concerns \u2014 it will give you direct hands-on access so you can form your own judgment.",
    training: 'The live calibration session is specifically designed to be low-stakes before anything goes live.',
  },
  Complacent: {
    color: '#1E40AF', bg: '#EFF6FF', border: '#93C5FD', icon: '\u25a0',
    tagline: "Not worried about AI \u2014 and not yet convinced it changes much.",
    desc: "You're not anxious about this, which is fine. But if you haven't seen what AI-assisted proposal pipelines actually produce \u2014 the outputs, the market intelligence, the opportunity rankings \u2014 you might be surprised by what's already possible.",
    training: "The live demo is where this usually lands. See it first, then form the opinion.",
  },
}
